name: Build Anki Deck

on:
  push:
    branches: [ main, master ]
    tags: [ "v*" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: |
          python -m pip install -U pip
          pip install -r build/requirements.txt
      - run: python build/build.py
      - uses: actions/upload-artifact@v4
        with:
          name: os_theory
          path: |
            os_theory.apkg
            os_theory-v*.apkg

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with: { name: os_theory, path: . }
      - uses: softprops/action-gh-release@v2
        with:
          files: |
            os_theory.apkg
            os_theory-v*.apkg
