name: Build & Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write   # <-- add this line

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -r build/requirements.txt

      - name: Build Anki deck
        run: python build/build.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: os_theory
          path: os_theory.apkg

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write   # <-- required for create-release
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: os_theory
          path: .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: os_theory.apkg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
